export const MIGRATIONS:string[]=[
  `
  CREATE TABLE IF NOT EXISTS __migrations (id INTEGER PRIMARY KEY);
  CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, category_id INTEGER, amount REAL NOT NULL, currency TEXT NOT NULL, ts TEXT NOT NULL, note TEXT, FOREIGN KEY (category_id) REFERENCES categories(id));
  CREATE TABLE IF NOT EXISTS rates (id INTEGER PRIMARY KEY AUTOINCREMENT, base TEXT NOT NULL, quote TEXT NOT NULL, value REAL NOT NULL, ts TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, body TEXT, ts TEXT NOT NULL);
  `
];