default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      workspace: "FundMind.xcworkspace",
      scheme: "FundMind",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end
