param()
$projectRoot = "D:\FundMind"
Set-Location $projectRoot

# 0) wyczyść cache Metro (opcjonalnie folder .expo)
if (Test-Path ".expo") { Remove-Item -Recurse -Force ".expo" }

# 1) zależności (UI + pickery + dayjs)
npm install react-native-calendars @react-native-picker/picker dayjs

# 2) TSX (premium) zapis przez Base64, więc PowerShell NIC nie popsuje
$tsxBase64 = @"
aW1wb3J0IFJlYWN0LCB7IHVzZU1lbW8sIHVzZVN0YXRlIH0gZnJvbSAncmVhY3QnOwppbXBvcnQgeyBWaWV3LCBUZXh0LCBTdHls
ZVNoZWV0IH0gZnJvbSAncmVhY3QtbmF0aXZlJzsKaW1wb3J0IHsgQ2FsZW5kYXIgfSBmcm9tICdyZWFjdC1uYXRpdmUtY2FsZW5k
YXJzJzsKaW1wb3J0IHsgUGlja2VyIH0gZnJvbSAnQHJlYWN0LW5hdGl2ZS1waWNrZXIvcGlja2VyJzsKaW1wb3J0IGRheWpzIGZy
b20gJ2RheWpzJzsKaW1wb3J0IHsgU3RhY2sgfSBmcm9tICdleHBvLXJvdXRlcic7CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBD
YWxlbmRhclNjcmVlbigpIHsKICBjb25zdCBbeWVhciwgc2V0WWVhcl0gPSB1c2VTdGF0ZTxudW1iZXI+KGRheWpzKCkueWVhcigp
KTsKICBjb25zdCBbbW9udGgsIHNldE1vbnRoXSA9IHVzZVN0YXRlPG51bWJlcj4oZGF5anMoKS5tb250aCgpICsgMSk7CiAgY29u
c3QgW2RheSwgc2V0RGF5XSA9IHVzZVN0YXRlPG51bWJlcj4oZGF5anMoKS5kYXRlKCkpOwogIGNvbnN0IFtob3VyLCBzZXRIb3Vy
XSA9IHVzZVN0YXRlPG51bWJlcj4oZGF5anMoKS5ob3VyKCkpOwogIGNvbnN0IFttaW51dGUsIHNldE1pbnV0ZV0gPSB1c2VTdGF0
ZTxudW1iZXI+KGRheWpzKCkubWludXRlKCkpOwogIGNvbnN0IFtzZWxlY3RlZERhdGUsIHNldFNlbGVjdGVkRGF0ZV0gPSB1c2VT
dGF0ZTxzdHJpbmc+KGRheWpzKCkuZm9ybWF0KCdZWVlZLU1NLUREJykpOwoKICBjb25zdCB5ZWFycyA9IHVzZU1lbW8oKCkgPT4g
QXJyYXkuZnJvbSh7IGxlbmd0aDogMjEgfSwgKF8sIGkpID0+IDIwMjAgKyBpKSwgW10pOwogIGNvbnN0IG1vbnRocyA9IHVzZU1l
bW8oKCkgPT4gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTIgfSwgKF8sIGkpID0+IGkgKyAxKSwgW10pOwogIGNvbnN0IGRheXNJbk1v
bnRoID0gdXNlTWVtbygoKSA9PiBkYXlqcyhgJHt5ZWFyfS0ke1N0cmluZyhtb250aCkucGFkU3RhcnQoMiwnMCcpfS0wMWApLmRh
eXNJbk1vbnRoKCksIFt5ZWFyLCBtb250aF0pOwogIGNvbnN0IGRheXMgPSB1c2VNZW1vKCgpID0+IEFycmF5LmZyb20oeyBsZW5n
dGg6IGRheXNJbk1vbnRoIH0sIChfLCBpKSA9PiBpICsgMSksIFtkYXlzSW5Nb250aF0pOwogIGNvbnN0IGhvdXJzID0gdXNlTWVt
bygoKSA9PiBBcnJheS5mcm9tKHsgbGVuZ3RoOiAyNCB9LCAoXywgaSkgPT4gaSksIFtdKTsKICBjb25zdCBtaW51dGVzID0gdXNl
TWVtbygoKSA9PiBBcnJheS5mcm9tKHsgbGVuZ3RoOiA2MCB9LCAoXywgaSkgPT4gaSksIFtdKTsKCiAgcmV0dXJuICgKICAgIDxW
aWV3IHN0eWxlPXtzdHlsZXMuY29udGFpbmVyfT4KICAgICAgPFN0YWNrLlNjcmVlbiBvcHRpb25zPXt7IHRpdGxlOiAnS2FsZW5k
YXJ6IFByZW1pdW0nIH19IC8+CiAgICAgIDxDYWxlbmRhciBjdXJyZW50PXtzZWxlY3RlZERhdGV9CiAgICAgICAgb25EYXlQcmVz
cz17KGQpID0+IHsKICAgICAgICAgIHNldFNlbGVjdGVkRGF0ZShkLmRhdGVTdHJpbmcpOwogICAgICAgICAgY29uc3QgdiA9IGRh
eWpzKGQuZGF0ZVN0cmluZyk7CiAgICAgICAgICBzZXRZZWFyKHYueWVhcigpKTsKICAgICAgICAgIHNldE1vbnRoKHYubW9udGgo
KSArIDEpOwogICAgICAgICAgc2V0RGF5KHYuZGF0ZSgpKTsKICAgICAgICB9fQogICAgICAgIG1hcmtlZERhdGVzPXsgW3NlbGVj
dGVkRGF0ZV06IHsgc2VsZWN0ZWQ6IHRydWUsIG1hcmtlZDogdHJ1ZSB9IH0KICAgICAgLz4KCiAgICAgIDxWaWV3IHN0eWxlPXtz
dHlsZXMucm93fT4KICAgICAgICA8UGlja2VyIHN0eWxlPXtzdHlsZXMucGlja2VyfSBzZWxlY3RlZFZhbHVlPXt5ZWFyfSBvblZh
bHVlQ2hhbmdlPXsodikgPT4gc2V0WWVhcihOdW1iZXIodikpfT4KICAgICAgICAgIHt5ZWFycy5tYXAoKHkpID0+IDxQaWNrZXIu
SXRlbSBrZXk9e3l9IGxhYmVsPXtTdHJpbmcoeSl9IHZhbHVlPXt5fSAvPil9CiAgICAgICAgPC9QaWNrZXI+CiAgICAgICAgPFBp
Y2tlciBzdHlsZT17c3R5bGVzLnBpY2tlcn0gc2VsZWN0ZWRWYWx1ZT17bW9udGh9IG9uVmFsdWVDaGFuZ2U9eyh2KSA9PiBzZXRN
b250aChOdW1iZXIodikpfT4KICAgICAgICAgIHttb250aHMubWFwKChtKSA9PiA8UGlja2VyLkl0ZW0ga2V5PXttfSBsYWJlbD17
U3RyaW5nKG0pLnBhZFN0YXJ0KDIsJzAnKX0gdmFsdWU9e219IC8+KX0KICAgICAgICA8L1BpY2tlcj4KICAgICAgICA8UGlja2Vy
IHN0eWxlPXtzdHlsZXMucGlja2VyfSBzZWxlY3RlZFZhbHVlPXtkYXl9IG9uVmFsdWVDaGFuZ2U9eyh2KSA9PiBzZXREYXkoTnVt
YmVyodikpfT4KICAgICAgICAgIHtkYXlzLm1hcCgoZCkgPT4gPFBpY2tlci5JdGVtIGtleT17ZH0gbGFiZWw9e1N0cmluZyhkKS5w
YWRTdGFydCgyLCcwJyl9IHZhbHVlPXtkfSAvPil9CiAgICAgICAgPC9QaWNrZXI+CiAgICAgIDwvVmlldz4KCiAgICAgIDxWaWV3
IHN0eWxlPXtzdHlsZXMucm93fT4KICAgICAgICA8UGlja2VyIHN0eWxlPXtzdHlsZXMucGlja2VyfSBzZWxlY3RlZFZhbHVlPXto
b3VyfSBvblZhbHVlQ2hhbmdlPXsodikgPT4gc2V0SG91cihOdW1iZXIodikpfT4KICAgICAgICAgIHtob3Vycy5tYXAoKGgpID0+
IDxQaWNrZXIuSXRlbSBrZXk9e2h9IGxhYmVsPXtTdHJpbmcoaCkucGFkU3RhcnQoMiwnMCcpfSB2YWx1ZT17aH0gLz4pfQogICAg
ICAgIDwvUGlja2VyPgogICAgICAgIDxQaWNrZXIgc3R5bGU9e3N0eWxlcy5waWNrZXJ9IHNlbGVjdGVkVmFsdWU9e21pbnV0ZX0g
b25WYWx1ZUNoYW5nZT17KHYpID0+IHNldE1pbnV0ZShOdW1iZXIodikpfT4KICAgICAgICAgIHttaW51dGVzLm1hcCgobSkgPT4g
PFBpY2tlci5JdGVtIGtleT17bX0gbGFiZWw9e1N0cmluZyhtKS5wYWRTdGFydCgyLCcwJyl9IHZhbHVlPXttfSAvPil9CiAgICAg
ICAgPC9QaWNrZXI+CiAgICAgIDwvVmlldz4KCiAgICAgIDxUZXh0IHN0eWxlPXtzdHlsZXMuc2VsZWN0ZWR9PgogICAgICAgIFd5
YnJhbm86IHt5ZWFyfS17U3RyaW5nKG1vbnRoKS5wYWRTdGFydCgyLCcwJyl9LXtTdHJpbmcoZGF5KS5wYWRTdGFydCgyLCcwJyl9
IHtTdHJpbmcoaG91cikucGFkU3RhcnQoMiwnMCcpfTp7U3RyaW5nKG1pbnV0ZSkucGFkU3RhcnQoMiwnMCcpfQogICAgICA8L1Rl
eHQ+CiAgICA8L1ZpZXc+CiAgKTsKfQoKY29uc3Qgc3R5bGVzID0gU3R5bGVTaGVldC5jcmVhdGUoewogIGNvbnRhaW5lcjogeyBm
bGV4OiAxLCBwYWRkaW5nOiAxNiB9LAogIHJvdzogeyBmbGV4RGlyZWN0aW9uOiAncm93JywgbWFyZ2luVmVydGljYWw6IDggfSwK
ICBwaWNrZXI6IHsgZmxleDogMSB9LAogIHNlbGVjdGVkOiB7IG1hcmdpblRvcDogMTYsIGZvbnRTaXplOiAxNiwgZm9udFdlaWdo
dDogJzYwMCcsIHRleHRBbGlnbjogJ2NlbnRlcicgfSwKfSk7Cg==
"@

$calDir = Join-Path $projectRoot "app\calendar"
New-Item -ItemType Directory -Force -Path $calDir | Out-Null
$calPath = Join-Path $calDir "index.tsx"
[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($tsxBase64)) | Set-Content -Encoding UTF8 $calPath

# 3) dopnij zakładkę w tabs/_layout.tsx (jeśli istnieje)
$tabsLayout = Join-Path $projectRoot "app\(tabs)\_layout.tsx"
if (Test-Path $tabsLayout) {
  $c = Get-Content $tabsLayout -Raw
  if ($c -notmatch "name='calendar'") {
    $c2 = $c -replace '(<Tabs>)', "`$1`r`n      <Tabs.Screen name='calendar' options={{ title: 'Kalendarz Premium' }} />"
    $c2 | Set-Content -Encoding UTF8 $tabsLayout
  }
}

# 4) start Expo z czystym cache
npx expo start -c --port 8081 --host lan
