name: CI Sanity

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  sanity:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Workflow YAML is valid and runs."
