name: commitlint
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
