name: EAS Preview

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build-preview:
    name: Build (Android/iOS) preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (robust)
        run: |
          set -e
          if npm ci; then
            echo "✓ npm ci OK"
          else
            echo "::warning::npm ci failed — retrying npm install --legacy-peer-deps"
            npm install --legacy-peer-deps
          fi

      - name: Setup Expo & EAS
        uses: expo/expo-github-action@v8
        with:
          expo-cache: true
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android (preview)
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: npx eas build --platform android --profile preview --non-interactive --no-wait

      - name: Build iOS (preview)
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: npx eas build --platform ios --profile preview --non-interactive --no-wait
