name: Checks + (optional) EAS

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (robust)
        run: |
          set -e
          npm ci || npm i --legacy-peer-deps || npm i --no-optional --legacy-peer-deps

      - name: Lint
        run: npm run lint --silent || true

      - name: Typecheck
        run: npm run typecheck --silent || true

      - name: Tests (jest)
        run: npm run test:ci --silent || true

  eas:
    needs: [checks]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (robust)
        run: |
          set -e
          npm ci || npm i --legacy-peer-deps || npm i --no-optional --legacy-peer-deps

      - name: Setup EAS CLI
        run: npm i -g eas-cli || true

      - name: Guard EXPO_TOKEN
        id: guard
        shell: bash
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "::notice ::EXPO_TOKEN missing → skipping EAS."
            echo "skip=1" >> $GITHUB_OUTPUT
          else
            echo "skip=0" >> $GITHUB_OUTPUT
          fi

      - name: EAS whoami (soft)
        if: steps.guard.outputs.skip == '0'
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami --token "$EXPO_TOKEN" || true

      - name: EAS build (android preview, soft)
        if: steps.guard.outputs.skip == '0'
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile preview --non-interactive --no-wait --token "$EXPO_TOKEN" || true