name: Expo EAS CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ "v*" ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    name: Checks (lint/tsc/jest – soft)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (ultra-robust, soft)
        shell: bash
        continue-on-error: true
        run: |
          set -e
          echo "→ npm ci"
          npm ci \
          || (echo "ci failed → npm i --legacy-peer-deps" && npm i --legacy-peer-deps) \
          || (echo "fallback → npm i --no-optional --legacy-peer-deps" && npm i --no-optional --legacy-peer-deps) \
          || (echo "final fallback → npm i --force --legacy-peer-deps" && npm i --force --legacy-peer-deps) \
          || (echo "::notice ::Install failed (soft) — continuing anyway." && true)

      - name: Lint
        continue-on-error: true
        run: npm run -s lint || echo "::notice ::lint skipped/failure (soft)"

      - name: Typecheck
        continue-on-error: true
        run: npm run -s typecheck || echo "::notice ::typecheck skipped/failure (soft)"

      - name: Tests
        continue-on-error: true
        run: npm run -s test:ci || npm test --passWithNoTests || echo "::notice ::tests skipped/failure (soft)"

  eas:
    name: EAS preview (on tag v* if EXPO_TOKEN)
    needs: [checks]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (soft)
        shell: bash
        continue-on-error: true
        run: |
          set -e
          npm ci || npm i --legacy-peer-deps || npm i --no-optional --legacy-peer-deps || true

      - name: Setup EAS CLI
        run: npm i -g eas-cli

      - name: Guard EXPO_TOKEN
        id: guard
        shell: bash
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "::notice ::EXPO_TOKEN missing → skipping EAS."
            echo "skip=1" >> $GITHUB_OUTPUT
          else
            echo "skip=0" >> $GITHUB_OUTPUT
          fi

      - name: EAS whoami
        if: steps.guard.outputs.skip == '0'
        env: { EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} }
        run: eas whoami --token "$EXPO_TOKEN"

      - name: EAS build (android preview)
        if: steps.guard.outputs.skip == '0'
        env: { EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} }
        run: eas build --platform android --profile preview --non-interactive --no-wait --token "$EXPO_TOKEN"