name: Checks (green base)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Echo success
        run: |
          echo "All good ✅"
          exit 0